### ISSUE TITLE
Git Convention

### ISSUE THREAD

**Issue by jeongjae96** [jeongjae96/synthesis-car-od#1]
## Description
- 깃을 통한 협업을 위해 Convention 정하기

## Tasks
- [x] Commit message convention 정하기
- [x] Issue Template 정하기
- [x] Label 정하기
- [x] Branch convention 정하기
