### ISSUE TITLE
데이터 전처리 코드 정리

### ISSUE THREAD

**Issue by jeongjae96** [jeongjae96/synthesis-car-od#19]
## Description
- 저희에게 제공된 데이터 포맷을 COCO, YOLO format으로 변환해 여러 모델에 사용 예정입니다. 현재 ```examples/data_preprocessing``` 폴더에 각자 전처리 코드를 구현했는데, 정리해보고자 합니다.

## Tasks
- [x] convert our train & test data to COCO format
- [x] split COCO data using stratified group kfold
- [x] convert our train & test data to YOLO format
- [x] split YOLO data using stratified group kfold
