### ISSUE TITLE
Train Data Mean & Standard Deviation 구하기

### ISSUE THREAD

**Issue by jeongjae96** [jeongjae96/synthesis-car-od#22]
## Description
- torchvision faster r-cnn augmentation 실험을 진행하며, normalize가 2번 들어가거나 normalize 이후 colorjitter를 넣었더니 성능이 올라가는 신기한 현상을 겪었습니다. 이것을 보고 저희 데이터의 mean, std를 이용하는 것이 성능 향상에 도움이 될 수도 있겠다라는 생각이 들어, ImageNet의 mean, std 대신 저희 훈련 데이터의 mean, std를 이용해 normalize를 해보고자 합니다.

## Tasks
- [x] Train data mean, std 구하기
- [x] GrayScale일 때 mean, std 구하기
- [x] Train Data의 mean, std를 이용해 normalize 후 torchvision faster r-cnn 모델 학습
