### ISSUE TITLE
competition 제출용 YOLO 소스 정리

### ISSUE THREAD

**Issue by updaun** [jeongjae96/synthesis-car-od#31]
## Description
- competition 제출을 위한 yolo pipeline 점검, 소스 정리

## Tasks
- [x] data preprocess (labelme 2 yolo)
- [x] yolo v7 train
- [x] yolo v7 test
- [x] yolo v7 inference result to labelme CSV file(submission)
---
- [x] yolo v8 train
- [x] yolo v8 test
- [x] yolo v8 inference result to labelme CSV file(submission)

**Comment by jeongjae96** [comment]
@updaun issue close 하겠습니다!
