### ISSUE TITLE
Train 데이터 EDA

### ISSUE THREAD

**Issue by jeongjae96** [jeongjae96/synthesis-car-od#5]
## Description
- Train 데이터에 대한 파악을 위해 EDA를 진행하고자 합니다.

## Tasks
- [x] 이미지 크기 확인
- [ ] bounding box 크기 확인
- [x] 클래스별 개수 확인
- [ ] 객체 개수 확인
