### ISSUE TITLE
MMDetection 구축

### ISSUE THREAD

**Issue by jeongjae96** [jeongjae96/synthesis-car-od#7]
## Description
- MMDetection을 사용한 모델링 구축

## Tasks
- [x] MMDetection Documentation을 통한 사전 조사
- [x] Input 데이터 포맷 확인 및 data split
- [x] 모델 구축
- [ ] mAP@0.85 wandb logging
